# Generated by Django 4.1.1 on 2022-09-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='now',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
